name: "🌟 Add New Contributor"
about: "Add your profile to ContributorHub — perfect for beginners!"
labels: ["👋 new contributor", "✨ enhancement"]
assignees:
  - sujanthapa01
body:
  - type: markdown
    attributes:
      value: |
        # Welcome to ContributorHub! 🎉
        
        Thanks for wanting to contribute! This template helps us add your profile.
        
        **Great if you're:**  
        - New to open source  
        - Learning and building your portfolio  
        - Excited to join our community
        
  - type: input
    id: github_username
    attributes:
      label: 📝 GitHub Username
      placeholder: "e.g., sujanthapa01"
    validations:
      required: true

  - type: input
    id: display_name
    attributes:
      label: 🏷️ Display Name (Optional)
      placeholder: "e.g., Sujan Thapa"
    validations:
      required: false

  - type: input
    id: bio
    attributes:
      label: 📖 Short Bio (Optional)
      placeholder: "e.g., Student passionate about open source."
    validations:
      required: false

  - type: dropdown
    id: experience_level
    attributes:
      label: 🎯 Experience Level
      options:
        - "Complete Beginner"
        - "Some Experience"
        - "Intermediate"
        - "Experienced"
    validations:
      required: true

  - type: checkboxes
    id: motivation
    attributes:
      label: 🚀 Why contribute? (Select all that apply)
      options:
        - label: First open source contribution
        - label: Learn about open source
        - label: Build portfolio
        - label: Join the community
        - label: Help other beginners

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      options:
        - label: My GitHub profile is public with at least one repo
          required: true
        - label: I’ve read the [How to Contribute](https://docs.contributorhub.dev/tutorial-basics/how-to-contribute) guide
          required: true
        - label: I understand this is beginner-friendly
          required: true
        - label: I’m ready to follow the contribution steps
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## 🎉 Next Steps
        
        1. We review your request (within 24 hrs)  
        2. You get the green light to contribute  
        3. Follow the guide to add your profile  
        4. Your profile goes live! 🎊
        
        Need help? Ask here or email sujanthapa4001@gmail.com
        
        Welcome aboard! 🌟
