name: 🐛 Bug Report
description: Found something that's not working? Let us know so we can fix it!
title: "🐛 [Bug]: "
labels: ["🐛 bug", "🔍 needs triage"]
assignees:
  - sujanthapa01
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for helping us improve ContributorHub! 🛠️
        
        Found a bug? No worries - it happens to the best of us! This template will help us understand and fix the issue quickly.
        
        **Don't worry if you're not sure** - we'll help figure it out together! 😊
        
        ---

  - type: textarea
    id: bug_description
    attributes:
      label: 🐛 What went wrong?
      description: Tell us what happened in simple terms. Don't worry about being technical!
      placeholder: "e.g., When I click the 'Add Contributor' button, nothing happens..."
      rows: 3
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: ✅ What should have happened?
      description: What did you expect to happen instead?
      placeholder: "e.g., I expected my profile to be added to the contributors list..."
      rows: 2
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: 🔄 How can we reproduce this bug?
      description: Step-by-step instructions to recreate the problem
      placeholder: |
        1. Go to the website
        2. Click on '...'
        3. Fill in the form with '...'
        4. See error
      rows: 4
    validations:
      required: true

  - type: textarea
    id: error_messages
    attributes:
      label: ❌ Any error messages?
      description: Copy and paste any error messages you see (even if they look scary!)
      placeholder: "Paste any error messages here - don't worry about understanding them!"
      rows: 3
    validations:
      required: false

  - type: dropdown
    id: bug_area
    attributes:
      label: 🎯 Where did this happen?
      description: Which part of ContributorHub were you using?
      options:
        - "Website (contributorhub.dev)"
        - "Local development (npm start)"
        - "Python script (contributor_add.py)"
        - "Documentation"
        - "GitHub repository"
        - "I'm not sure"
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: 🌐 Which browser are you using?
      description: This helps us test the fix
      options:
        - "Chrome"
        - "Firefox"
        - "Safari"
        - "Edge"
        - "Other"
        - "I'm not sure"
    validations:
      required: false

  - type: dropdown
    id: operating_system
    attributes:
      label: 💻 What's your operating system?
      options:
        - "Windows"
        - "macOS"
        - "Linux"
        - "Other"
        - "I'm not sure"
    validations:
      required: false

  - type: checkboxes
    id: user_type
    attributes:
      label: 👤 What describes you best?
      options:
        - label: "New contributor (first time using ContributorHub)"
        - label: "Returning contributor"
        - label: "Developer working on the project"
        - label: "Just browsing the website"

  - type: textarea
    id: additional_context
    attributes:
      label: 📎 Anything else that might help?
      description: Screenshots, additional details, or anything else you think might be useful
      placeholder: "Feel free to add screenshots, links, or any other details that might help us understand the problem better!"
      rows: 3
    validations:
      required: false

  - type: checkboxes
    id: help_offer
    attributes:
      label: 🤝 Would you like to help fix this?
      description: No pressure! But if you're interested in learning...
      options:
        - label: "Yes, I'd like to learn how to fix this (with guidance!)"
        - label: "Maybe, if it's beginner-friendly"
        - label: "No, just reporting the bug"

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 🔧 What happens next?
        
        1. **We'll investigate** the issue and try to reproduce it
        2. **We'll ask for more info** if we need it
        3. **We'll work on a fix** and keep you updated
        4. **We'll let you know** when it's fixed!
        
        ## 🙏 Thank you!
        
        Bug reports help make ContributorHub better for everyone, especially beginners. Your feedback is valuable! 
        
        **Don't worry if you're not sure about something** - we're here to help figure it out together! 😊