name: Preview Deployment with PR Comment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Read Vercel config
        id: vercel-config
        run: |
          ORG_ID=$(jq -r '.orgId' .vercel/project.json)
          PROJECT_ID=$(jq -r '.projectId' .vercel/project.json)
          echo "ORG_ID=$ORG_ID" >> $GITHUB_OUTPUT
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_OUTPUT

      - name: Deploy preview to Vercel
        id: vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ steps.vercel-config.outputs.ORG_ID }}
          VERCEL_PROJECT_ID: ${{ steps.vercel-config.outputs.PROJECT_ID }}
        run: |
          vercel_output=$(npx vercel --token $VERCEL_TOKEN --yes --prebuilt --scope $VERCEL_ORG_ID --json)
          echo "$vercel_output"
          echo "url=$(echo $vercel_output | jq -r '.[0].url')" >> $GITHUB_OUTPUT

      - name: Comment PR with preview URL
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            🚀 Preview deployment is ready: ${{ steps.vercel.outputs.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
