name: Preview Deployment with PR Comment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy preview to Vercel
        id: vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          # Deploy with Vercel CLI and output JSON with deployment info
          vercel_output=$(npx vercel --token $VERCEL_TOKEN --yes --prebuilt --scope $VERCEL_ORG_ID --json)
          echo "$vercel_output"
          # Extract URL from the JSON output
          echo "url=$(echo $vercel_output | jq -r '.[0].url')" >> $GITHUB_OUTPUT

      - name: Comment PR with preview URL
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            🚀 Preview deployment is ready: ${{ steps.vercel.outputs.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
